### ISSUE TITLE
Initial Priorities checklist

### ISSUE THREAD

**Issue by Rekyt** [FRBCesab/funbiogeo#19]
I'm opening this issue to set up a check list of priorities we discussed at the CESAB meeting.

- [x] Reinstate site x locations objects as `sf` objects to make `extract()` work whatever the geometry (polygons, regular grids, points, lines, etc.) (is being handled by PR #20)
- [x] Add good quality example data in the package including (this should come soon with the `datasets` branch from @ahasverus) - handled by PR #22:
    - [x] site x species
    - [x] species x traits
    - [x] site x locations (that help have a nice map)
    - [x] site x environment (or we can extract the data, but it would be good to get at least one good trait-environment relationship) - Done using rasters stored in `inst/`
    - [x] not too big in size (< 5Mb to include it in the package)
    - [x] Create a long format example dataset based on new data (to be used with the function `fb_format_*()`)
- [x] Sites and species labels as a new column (no row names) (tackled in PR #23)
    - [x] In datasets
    - [x] In functions
- [x] Consider non-continuous traits in the package (tackled in PR #24 ):
    - [x] For trait coverage computation (can compute trait coverages with non-continuous trait)
    - [x] For CWM computation (cannot compute CWM)
    - [x] Think hard about having a trait description data.frame as done in `mFD` (we decided not to include one by default for one, this a package specific thing)
- [x] Add nice default visualizations (**tackled in #27** see #9, #10, #11):
    - [x] Nice default trait coverage visualization (# of traits vs. # of species?) (#9)
    - [ ] Generic site biplot function (site values vs. site value)
    - [x] Generic site mapping function (map of sites + mapped to site value)
    - [ ] Cover of site environmental space compared to available environmental space in source raster? (#10)
- [ ] Consider in computation and visualization a way to create discrete categories:
    - [ ] in sites (i.e. visualize site per biome)
    - [ ] in species (i.e. group species per family, per growth form, etc.) (#15) 
    - [ ] both
- [x] Think about potential temporal dimension inclusion (#13) 
    - [x] This could be a simple 3rd dimension to the site-species matrix
    - [x] Make sure it doesn't break previous framework and other functions
- [ ] Make it possible to include local trait measurements (#14)
    - [ ] Should this be an additional dimension to the array?
    - [ ] Maybe this would be easier if the whole dataset what in a `tidy` format?

**Comment by Rekyt** [comment]
Closing this issue (maybe temporarily) as most initial priorities are covered.
